### ISSUE TITLE
Create grpc integration tests

### ISSUE THREAD

**Issue by wfxr** [oom-ai/oomstore#600]
Task list:
- [x] #601
- [x] #614
- [x] #616
- [x] #622
- [x] #623
- [x] #624
- [x] #625
- [x] #692
- [x] #693

**Comment by YikSanChan** [comment]
Such logic currently exists in https://github.com/oom-ai/oomstore/blob/main/oomd/test/client.go

**Comment by wfxr** [comment]
@YikSanChan Got it.

**Comment by YikSanChan** [comment]
@wfxr Can we close this?
